### ISSUE TITLE
[Feature Request] Supports other JPA provider than hibernate

### ISSUE THREAD

**Issue by ghilainm** [kuros/random-jpa#22]
I would have been really happy to use your library however I can't as I am using a different JPA provider than you. I could probably use both in parallel but that wouldn't be convenient.

**Comment by kuros** [comment]
Can you let me know which JPA provider are you using

**Comment by ghilainm** [comment]
Thx for your quick answer ;-).

I am using TopLink, which is a wrapper around EclipseLink so it should work if you support EclipseLink.
Here is the maven dependency. This is the default JPA provider with WebLogic.

<dependency>
                <groupId>com.oracle.toplink</groupId>
                <artifactId>eclipselink</artifactId>
                <version>12.1.3-0-0</version>
                <scope>provided</scope>
            </dependency> 

By the way old hibernate version do not work either. It would be nice to know which JPA version you support.

**Comment by kuros** [comment]
I have started working on adding EclipseLink as provider, I will update you once it is completed

**Comment by kuros** [comment]
Random-JPA now supports EclipseLink, will be available with v0.4.10
