### ISSUE TITLE
Plan documentation out-of-sync with v1.0.3 API

### ISSUE THREAD

**Issue by Ansonator** [kuros/random-jpa#42]
`README.md`'s [creating-plan](https://github.com/kuros/random-jpa#creating-plan) and the Wiki section about plans are inconsistent with the latest version of the API.  The method [JpaContextImpl#create(Plan)](https://github.com/kuros/random-jpa/blob/v1.0.3/src/main/java/com/github/kuros/random/jpa/JPAContextImpl.java#L130) is private and not exposed in `JpaContext`.

**Comment by kuros** [comment]
Thanks for letting me know, I have update the docs
